[build]
  publish = "public"
  command = "npm run build --prefix-paths"
[build.environment]
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
[headers.values]
  Cache-Control = "public, max-age=360000" 
[[redirects]]
  from = "/cloud-typography/fonts.css"
  to = "https://cloud.typography.com/7369076/7111412/css/fonts.css"
  status = 200
[[redirects]]
  from = "/codeofconduct"
  to = "https://www.openstack.org/legal/community-code-of-conduct/"
  status = 302
[[redirects]]
  from = "/trademark"
  to = "https://www.openstack.org/brand/openstack-trademark-policy/"
  status = 302
[[redirects]]
  from = "https://www.osf.dev/*"
  to = "https://openinfra.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://osf.dev/*"
  to = "https://openinfra.dev/:splat"
  status = 301
  force = true
  
 
